// <auto-generated />
using FAQ.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FAQ.Migrations
{
    [DbContext(typeof(FaqDbContext))]
    partial class FaqDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FAQ.Models.Category", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Name");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Name = "General"
                        },
                        new
                        {
                            Name = "Maintenance"
                        },
                        new
                        {
                            Name = "History"
                        });
                });

            modelBuilder.Entity("FAQ.Models.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CategoryId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TopicId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("TopicId");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Answer = "They are very intelligent..",
                            CategoryId = "General",
                            QuestionText = "How intellegent are Retreivers?",
                            TopicId = "Retriever"
                        },
                        new
                        {
                            Id = 2,
                            Answer = "Regular grooming and vet check-ups are essential...",
                            CategoryId = "Maintenance",
                            QuestionText = "How do I maintain my Retriever?",
                            TopicId = "Retriever"
                        },
                        new
                        {
                            Id = 3,
                            Answer = "Retrievers were originally bred as hunting dogs...",
                            CategoryId = "History",
                            QuestionText = "What is the history of the Retriever breed?",
                            TopicId = "Retriever"
                        },
                        new
                        {
                            Id = 4,
                            Answer = "Chihuahuas typically weigh between 2-6 pounds...",
                            CategoryId = "General",
                            QuestionText = "How big do Chihuahuas get?",
                            TopicId = "Chihuahua"
                        },
                        new
                        {
                            Id = 5,
                            Answer = "Adult Chihuahuas should be fed 2-3 times a day...",
                            CategoryId = "Maintenance",
                            QuestionText = "How often should I feed my Chihuahua?",
                            TopicId = "Chihuahua"
                        },
                        new
                        {
                            Id = 6,
                            Answer = "Chihuahuas are believed to have originated in Mexico...",
                            CategoryId = "History",
                            QuestionText = "What is the origin of the Chihuahua breed?",
                            TopicId = "Chihuahua"
                        },
                        new
                        {
                            Id = 7,
                            Answer = "Pomeranians can be good with kids if socialized early...",
                            CategoryId = "General",
                            QuestionText = "Are Pomeranians good with kids?",
                            TopicId = "Pomeranian"
                        },
                        new
                        {
                            Id = 8,
                            Answer = "Regular brushing and occasional baths are recommended...",
                            CategoryId = "Maintenance",
                            QuestionText = "How do I groom my Pomeranian?",
                            TopicId = "Pomeranian"
                        },
                        new
                        {
                            Id = 9,
                            Answer = "Pomeranians are descended from large sled dogs...",
                            CategoryId = "History",
                            QuestionText = "What is the history of the Pomeranian breed?",
                            TopicId = "Pomeranian"
                        });
                });

            modelBuilder.Entity("FAQ.Models.Topic", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Name");

                    b.ToTable("Topics");

                    b.HasData(
                        new
                        {
                            Name = "Retriever"
                        },
                        new
                        {
                            Name = "Chihuahua"
                        },
                        new
                        {
                            Name = "Pomeranian"
                        });
                });

            modelBuilder.Entity("FAQ.Models.Question", b =>
                {
                    b.HasOne("FAQ.Models.Category", "Category")
                        .WithMany("Questions")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FAQ.Models.Topic", "Topic")
                        .WithMany("Questions")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("FAQ.Models.Category", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("FAQ.Models.Topic", b =>
                {
                    b.Navigation("Questions");
                });
#pragma warning restore 612, 618
        }
    }
}
